version: "2.22"

services:

  eureka:
    image: eureka-service:latest
    ports:
      - "8761:8761"

  user:
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - eureka

  product:
    image: product-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  guarantee:
    image: guarantee-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - eureka

  report:
    image: report-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - eureka

  purchase:
    image: purchase-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - eureka

  gateway:
    image: gateway-service:latest
    ports:
      - "8765:8765"
    depends_on:
      - eureka

