package com.shopproject.purchase.entities;

public enum Status {
    WAITING_FOR_PAYMENT,
    WAITING_FOR_MAKE_GUARANTEE,
    WAITING_FOR_REFUND_OF_PAYMENT,
    WAITING_FOR_PUT_BACK_PRODUCT,
    WAITING_FOR_REFUND_MONEY,
    WAITING_FOR_RETURN_PRODUCT,
    PURCHASED,
    REFUND,
    PURCHASE_ERROR
    }
